### ISSUE TITLE
Make validate_histos.py from the IRIS-HEP repo pass on RDF's output histograms

### ISSUE THREAD

**Issue by eguiraud** [root-project/analysis-grand-challenge#28]

**Comment by eguiraud** [comment]
I guess the important underlying question is: do you think the current agreement (and the current state of the implementation) is good enough that we can tag a v1?

**Comment by eguiraud** [comment]
I just checked for the current version of main (6c7e045cbbdae84756).

It turns out that the only mismatches are caused by:
- bin migrations, which the latest version of the `validate_histograms.py` script from the reference implementation handles automatically
- a problem with the reference implementation: it artificially adds 1e-6 to all bin contents. this will be fixed there: https://github.com/iris-hep/analysis-grand-challenge/issues/166#issuecomment-1642607883

The IRIS-HEP implementation should tag a v1.2 version soon that solves these issues. Then our outputs should pass the validation script, as far as I can tell. I'll leave this open until then.

One question remaining (for @andriiknu and @alexander-held): the RDF implementation does not produce histograms 4j1b_pseudodata and 4j2b_pseudodata: should it?

**Comment by alexander-held** [comment]
> One question remaining (for @andriiknu and @alexander-held): the RDF implementation does not produce histograms 4j1b_pseudodata and 4j2b_pseudodata: should it?

I would say we do not explicitly require those histograms to be written out in the analysis task. They are needed for the statistical inference stage, and https://agc.readthedocs.io/en/latest/taskbackground.html#statistical-model describes how to obtain them, but they are built from other histograms (which by themselves are required). In that sense I would argue that it is left up to the implementation to decide whether to write out dedicated histograms (and then use those for the dataset to fit the statistical model to) or to build that dataset on-the-fly from the required histograms at a later stage.

**Comment by andriiknu** [comment]
@eguiraud , @alexander-held 
`Jet_btag` inconsistency in selection cuts can be summarized via the following:
1. `4j1b` region is produced by NOT strict condition (`btag>=0.5`) in the selection cut ([main implementation](https://github.com/iris-hep/analysis-grand-challenge/blob/main/analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py#L257), [v1.1.0 implementation](https://github.com/iris-hep/analysis-grand-challenge/blob/v1.1.0/analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py#L226))
2. `4j2b` region (`btag>0.5`) and `trijet` use strict conditions (`trijet_btag>0.5`) as a selection cut

**Comment by eguiraud** [comment]
Thank you @andriiknu , the reference implementation will soon release a v1.2 tag which will use `>` everywhere. This is tracked in https://github.com/iris-hep/analysis-grand-challenge/issues/174 now

**Comment by eguiraud** [comment]
@alexander-held then should `validate_histograms.py` ignore 4j1b_pseudodata and 4j2b_pseudodata?

**Comment by alexander-held** [comment]
Good point, it doesn't do harm to have them in the reference files but we should just skip that comparison if the histograms were not produced by a given implementation.

**Comment by eguiraud** [comment]
Cool, I'll open a PR in a few minutes

**Comment by eguiraud** [comment]
Alright, I think the little mismatches we currently have are all understood.

I think we'll just wait for the reference implementation to tag a v1.2, adapt to that (e.g. making the btag cuts more uniform) and we'll tag a v1.0 of the RDF implementation!

If v1.2 will also remove the 1e-6 offsetting of the histogram bin contents mentioned at https://github.com/iris-hep/analysis-grand-challenge/issues/166#issuecomment-1642607883 we should have perfect agreement between our output histograms. Otherwise that's the one remaining snag and we'll sync up in v2.
